---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: heading
    label: Data
  - type: directory
    path: src/data
    label: Data
    create: all
    match: '**/*.yml'
  - type: document
    path: src/data/global/categories.yaml
    label: Categories
  - type: heading
    label: Blog
  - type: directory
    path: src/content
    label: Blog posts
    create: documents
    match: '*.md'
    new_doc_ext: md
    templates:
      - blog-post
  - type: document
    path: src/config/settings.json
    label: Config
upload_dir: ''
public_path: ''
front_matter_path: '/sssss'
use_front_matter_path:
file_template: ':filename:'
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: '/srv'
  working_dir: '/srv'
  instant_preview_command: npm run develop
