---
label: b_meta
hide_body: true
fields:
- name: meta
  type: field_group
  config: {}
  fields:
  - name: description
    type: text
    config:
      required: false
    label: Description
  - name: keywords
    type: tag_list
    default: []
    label: Keywords
  label: Meta
