---
label: Meta
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
    max: 60
  label: Title
  description: Meta title
- name: description
  type: text
  config:
    required: true
    max: 160
  label: Description
  description: Meta description
- name: keywords
  type: tag_list
  default: []
  label: Keywords
  description: Meta keywords
